# Generated by Django 5.0.6 on 2024-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_panelrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPanelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_features', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('custom_message', models.TextField(default='')),
            ],
        ),
    ]
